### ISSUE TITLE
Proposal: Add byName to getBean, etc...

### ISSUE THREAD

**Issue by dave08** [micronaut-projects/micronaut-kotlin#118]
Something like:

```kotlin
inline fun <reified T> BeanLocator.getBean(byName: String? = null): T = if (byName == null)
    getBean(T::class.java)
else
    getBean(T::class.java, Qualifiers.byName(byName))
```
this would not change anything for those already using the function, it would just add the extra byName capacity.

**Comment by sulume** [comment]
Is it extended only to getBean() but not to other variants such as findBean()?
