### ISSUE TITLE
RequestScope

### ISSUE THREAD

**Issue by ikovalyov** [micronaut-projects/micronaut-kotlin#21]
Micronaut 1.2 added support for the RequestScope beans. Unfortunately it's implementation relies on the `ServerRequestContext.currentRequest()` which is using `ThreadLocal`. In kotlin we're using coroutines and execution thread can be shared between several coroutines or same coroutine can start in one thread and finish in another. It makes impossible to use any logic bound to the `ThreadLocal`. Is it possible to have another, probably kotlin-specific, implementation of the request scope which does not rely on the `ThreadLocal` data?

**Comment by graemerocher** [comment]
This seems to be related to this comment https://github.com/micronaut-projects/micronaut-kotlin/issues/4#issuecomment-567987805

**Comment by willbuck** [comment]
@ikovalyov would you agree with Graeme's assessment that #4 captures your feature request?

**Comment by ikovalyov** [comment]
@willbuck I don't think so.
To be able to use thread-local variables we need to have an easy way to access variable and pass it to the coroutine as context element.

See  https://github.com/Kotlin/kotlinx.coroutines/blob/master/docs/coroutine-context-and-dispatchers.md#thread-local-data as example.

Thanks.

**Comment by ikovalyov** [comment]
Hi.
I created a repo which demonstrates the issue for RequestScope and ThreadLocal beans.
https://github.com/ikovalyov/micronaut-beans

Here you can see failing tests:
https://github.com/ikovalyov/micronaut-beans/runs/784388659?check_suite_focus=true

**Comment by willbuck** [comment]
Thanks for that @ikovalyov! My gut is that this is a larger feature to add, but I'd welcome you to take a shot at PR'ing an implementation as it seems like a useful thing to have! @jameskleeh @graemerocher what do you think?

**Comment by piotrek-py** [comment]
Any updates? The issue has a big impact on Kotlin code. Without RequestScope is too much boilerplate in code @willbuck @jameskleeh

**Comment by edrd-f** [comment]
I'll try to solve this. For anyone interested in helping, [this answer by Elizarov](https://stackoverflow.com/a/46227463) looks like a good start. The `CoroutineInterceptor` could be implemented by Micronaut's [CustomContinuation](https://github.com/micronaut-projects/micronaut-core/blob/master/http/src/main/kotlin/io/micronaut/http/bind/binders/ContinuationArgumentBinder.kt#L49).

**Comment by piotrek-py** [comment]
how things are going?

**Comment by edrd-f** [comment]
Hey @piotrek-py, I've played with this a little bit but didn't find an easy way to write a good test. It will take some more time, sorry.

**Comment by jameskleeh** [comment]
This has been resolved
