### ISSUE TITLE
Configuration Reference is broken

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-kotlin#251]
<img width="1175" alt="Screenshot 2021-03-27 at 10 28 53" src="https://user-images.githubusercontent.com/864788/112716535-44ee7580-8ee7-11eb-8de1-4b9de8387956.png">

**Comment by timyates** [comment]
There's no @ConfigurationProperties, so no Configuration Reference.  This is as expected (though does look a bit odd)
