### ISSUE TITLE
Compiling Kotlin app to native image is broken since Micronaut 2.4.1

### ISSUE THREAD

**Issue by vonZeppelin** [micronaut-projects/micronaut-kotlin#257]
### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Compile Kotlin Micronaut app that has `jackson-module-kotlin` as a dependency.

### Expected Behaviour

It is possible to compile the app into native image.

### Actual Behaviour

Native image compilation step throws an error
```
Error: Classes that should be initialized at run time got initialized during image building:
 kotlin.ULong was unintentionally initialized at build time. com.fasterxml.jackson.module.kotlin.UnsignedNumbersKt caused initialization of this class with the following trace: 
	at kotlin.ULong.<clinit>(ULong.kt)
	at com.fasterxml.jackson.module.kotlin.UnsignedNumbersKt.<clinit>(UnsignedNumbers.kt:22)
```

### Notes
Micronaut 2.4.1+ brings Jackson 2.12.2 which introduced support for Kotlin unsigned numbers (de-)serialization. Adding the `@TypeHint(typeNames = ["com.fasterxml.jackson.module.kotlin.UnsignedNumbersKt"])` annotation to the root app class helps fix this issue and native image compilation succeeds.

### Environment Information

- **Operating System**: macOS 10.15
- **Micronaut Version:** 2.4.1, 2.4.2
- **JDK Version:** GraalVM CE Java 11 21.0.0

### Example Application

**Comment by veN1337** [comment]
I can confirm this problem with Micronaut 2.4.1, 2.4.2 and 2.4.3-SNAPSHOT on Windows 10 and/or Docker Container with `graalvm-ce:java11-21.0.0.2` image.

This happen with Maven and Gradle (Kotlin). I didn't try "normal" Gradle (Groovy).

As reproducible example one can take a basic Micronaut application from Micronaut CLI or https://micronaut.io/launch:
`mn create-app --build=maven --jdk=11 --lang=kotlin --test=junit com.example.demo` or `mn create-app --build=gradle_kotlin --jdk=11 --lang=kotlin --test=junit com.example.demo`.
