### ISSUE TITLE
kotlin-extension-functions splits packages with io.micronaut.runtime, io.micronaut.http, and io.micronaut.inject

### ISSUE THREAD

**Issue by MT-Jacobs** [micronaut-projects/micronaut-kotlin#285]
### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Build project with `./gradlew clean build`

### Expected Behaviour

The project builds.

### Actual Behaviour

`kotlin_extension_functions` has a split-package issue with `io.micronaut.runtime`, `io.micronaut.http`, and `io.micronaut.inject` like so:

```
error: module io.micronaut.http reads package io.micronaut.scheduling from both io.micronaut.runtime and io.micronaut.kotlin.kotlin_extension_functions
error: module io.micronaut.http reads package io.micronaut.inject from both io.micronaut.inject and io.micronaut.kotlin.kotlin_extension_functions
error: module io.micronaut.http reads package io.micronaut.context from both io.micronaut.inject and io.micronaut.kotlin.kotlin_extension_functions
error: module io.micronaut.http reads package io.micronaut.runtime from both io.micronaut.runtime and io.micronaut.kotlin.kotlin_extension_functions
error: module io.micronaut.http reads package io.micronaut.http from both io.micronaut.kotlin.kotlin_extension_functions and io.micronaut.http
error: module io.micronaut.http reads package javax.annotation from both java.annotation and jsr305
error: module io.micronaut.core reads package io.micronaut.scheduling from both io.micronaut.runtime and io.micronaut.kotlin.kotlin_extension_functions
error: module io.micronaut.core reads package io.micronaut.inject from both io.micronaut.inject and io.micronaut.kotlin.kotlin_extension_functions
error: module io.micronaut.core reads package io.micronaut.context from both io.micronaut.inject and io.micronaut.kotlin.kotlin_extension_functions
error: module io.micronaut.core reads package io.micronaut.runtime from both io.micronaut.runtime and io.micronaut.kotlin.kotlin_extension_functions
error: module io.micronaut.core reads package io.micronaut.http from both io.micronaut.kotlin.kotlin_extension_functions and io.micronaut.http
error: module io.micronaut.core reads package javax.annotation from both java.annotation and jsr305
```

What this means is Micronaut with Kotlin is incompatible with the Java Platform Module System.

Note that I'm using Kotlin 1.5.20-M1 to resolve the issue with kapt found in https://youtrack.jetbrains.com/issue/KT-32202. You can swap out 1.5.20-M1 for 1.5.10 and remove kapt and the issue will persist. I'm happy to make the change to my repo if you'd like.

My assumptions of ways we could resolve this:

1. Use the [Gradle Modules Plugin ](https://github.com/java9-modularity/gradle-modules-plugin) to patch `micronaut-inject`, `micronaut_runtime`, and `micronaut-http` JARs into the `kotlin_extension_functions` module, then force `kotlin_extension_functions` to export those packages (though I tried this and couldn't get it to work).
2. Repackage `kotlin_extension_functions` to remove the split package. This is probably a big breaking change.
3. Create new dependencies that properly(?) package the injection, runtime, and http extension function on top of the injection/runtime/http modules.

Anyhow, I think my team is going to abandon working in the JPMS for now, but if Micronaut wants to support it _and_ Kotlin together, this looks like a blocker.

### Environment Information

- **Operating System**: Mac OS
- **Micronaut Version:** 2.3.3
- **JDK Version:** 11

### Example Application

https://github.com/MT-Jacobs/jpms-kotlin-micronaut-issues

**Comment by MT-Jacobs** [comment]
Here's the patching I tried:

```
tasks.compileJava {
    extensions.configure<org.javamodularity.moduleplugin.extensions.CompileModuleOptions> {
        addExports = mapOf(
            Pair("io.micronaut.kotlin.kotlin_extension_functions/io.micronaut.http", "com.example"),
            Pair("io.micronaut.kotlin.kotlin_extension_functions/io.micronaut.inject", "com.example"),
            Pair("io.micronaut.kotlin.kotlin_extension_functions/io.micronaut.runtime", "com.example"))
    }
}

modularity {
    //patchModule("java.annotation", "jsr305-3.0.2.jar") // Not needed for example
    patchModule("io.micronaut.kotlin.kotlin_extension_functions", "micronaut-inject-2.3.3.jar")
    patchModule("io.micronaut.kotlin.kotlin_extension_functions", "micronaut-runtime-2.3.3.jar")
    patchModule("io.micronaut.kotlin.kotlin_extension_functions", "micronaut-http-2.3.3.jar")
}
```

Oh, and I suppose there's a package split with `io.micronaut.context` and `io.micronaut.scheduling` too:

<img width="462" alt="bulk-pricing-service_–_module-info_java__com_arrivelogistics_bulkpricing_application_" src="https://user-images.githubusercontent.com/30127627/121541664-20297a80-c9cd-11eb-9e79-04a34a46e01a.png">

**Comment by graemerocher** [comment]
As far as I understand this is how extension functions work, in that they have to be in the same package as what they apply to?

**Comment by MT-Jacobs** [comment]
That's not the case, but it is the convention, I think.

You can put extension functions into any package - you just then have to import that package to get those functions. What this means is that you may wind up importing both of these hypothetical packages. For instance, rather than:

```import io.micronaut.runtime.*

fun main(args: Array<String>) {
    startApplication<Micronaut>(*args) {
        packages("com/example")
    }
}```

or

```import io.micronaut.runtime.Micronaut
import io.micronaut.runtime.startApplication

fun main(args: Array<String>) {
    startApplication<Micronaut>(*args) {
        packages("com/example")
    }
}```

we have

```
import io.micronaut.runtime.Micronaut
import io.micronaut.kotlin.runtime.startApplication

fun main(args: Array<String>) {
    startApplication<Micronaut>(*args) {
        packages("com/example")
    }
}
```

All this is to say that it _could_ be in the same package still. It's just that we should have Kotlin extension modules that build on top of the Micronaut modules. That solution would likely make the dependencies more complicated though.

**Comment by MT-Jacobs** [comment]
I just realized that my above example is flawed - that's not an extension function, it's an inline one - but the premise is the same. You just import the extension function in the different package.
