### ISSUE TITLE
Unresolved directives in docs

### ISSUE THREAD

**Issue by melix** [micronaut-projects/micronaut-kotlin#329]
### Issue description

While working on a new version of the Micronaut Build plugin which adds validation of the generated Asciidoc documentation, it discovered that the Kotlin docs contain unresolved directives:

https://micronaut-projects.github.io/micronaut-kotlin/latest/guide/

Search for "Unresolved directive in <stdin>"

**Comment by graemerocher** [comment]
yeah plugins that fail on these would be great

**Comment by ilopmar** [comment]
Fixed by #351
