### ISSUE TITLE
Kotlin Coroutines

### ISSUE THREAD

**Issue by DuskoV** [micronaut-projects/micronaut-kotlin#4]
Micronaut is supporting Kotlin, and Kotlin issued coroutines for reactive/async programming. Is there a sample which would show how to use Kotlin coroutines within Micronaut?

Thanks

**Comment by damianw** [comment]
More specifically, the following would all be huge improvements for Kotlin coroutines support:
- Built-in support for `Deferred` return type in controllers (can currently be done manually using a filter)
- `suspend` functions in controllers
- `Deferred` return type in HTTP clients
- `suspend` functions in HTTP clients

(I can break these out into separate issues if that is more appropriate)

**Comment by cherrydev** [comment]
I would appreciate even some sort of example of a work-around.
I'm currently doing something like:
```
@Get
fun myControllerMethod() : CompletableFuture<ResultType> {
  return GlobalScope.async { ... }.asCompletableFuture()
}
```
but I suspect there might be problems with this.
Any advice?

**Comment by damianw** [comment]
One other necessary thing I remembered: support for instrumenting coroutine `Dispatcher`s in the same way that RxJava `Scheduler`s and such are instrumented.

@cherrydev For the moment, I'm doing something like this, using `kotlinx.coroutines.rx2` and `kotlinx.coroutines.jdk8`:
```kotlin
interface ControllerScope : CoroutineScope {
    // using RxJava scheduler for instrumentation
    override val coroutineContext: CoroutineContext
        get() = SchedulerCoroutineDispatcher(Schedulers.computation())
}

@Controller("/")
class MyController : ControllerScope {
    @Get("/")
    fun myControllerMethod(): CompletableFuture<ResultType> = future {
        // ...
    }
}
```

**Comment by cherrydev** [comment]
Strangely, the above didn't work and instead JSON serialized the state of the CompletableFuture, but when I changed it to use a Single, it worked perfectly:
```kotlin
@Controller("/")
class MyController : ControllerScope {
    @Get("/")
    fun myControllerMethod(): Single<ResultType> = rxSingle {
        // ...
    }
}
```

**Comment by damianw** [comment]
Hmm, the `CompletableFuture` should work fine... sounds like a bug. You're using the jdk8 `java.util.concurrent.CompletableFuture`?

**Comment by cherrydev** [comment]
Yes, that's what I'm using. I'm using micronaut 1.1.2

It returns something like: 
```json
{
  "isDone" : false,
  "isCancelled" : false,
  "isCompletedExceptionally" : false,
  "numberOfDependents" : 1
}
```
Those are the public bean properties of CompletableFuture.
The two exact changes I made was changing `future {` to `rxSingle {` and the return type from `CompletableFuture<ResultType>` to `Single<Result>`

**Comment by mattkendall** [comment]
I'm new to rxJava, Kotlin, and Micronaut, so please forgive me if this is a dumb question, but based on what I've managed to understand so far, Micronaut usually handles Scheduler selection/creation for you, i.e. if you use the `@Client` annotation it handles schedulers within the `RxHttpClient`. The above example using `rxSingle { ... }` is functional for me, but is the usage of the `computation` scheduler (or one of the other default rxJava schedulers) the best practice? Or is there some way to use Kotlin Coroutines and have the work scheduled by Micronaut?

Again, apologies if this is a dumb question.

**Comment by ikovalyov** [comment]
Right now if we use @Cacheable annotation with suspend function then internal kotlin continuation type is being cached as POJO. On another request to the method object is restored and application hangs forever.

**Comment by gnomeria** [comment]
Any updates?

**Comment by graemerocher** [comment]
Will see what I can do in the Micronaut 1.3 time frame in the meantime if anyone wants to have a go PRs welcome

**Comment by graemerocher** [comment]
A PR has been submitted for support in controllers https://github.com/micronaut-projects/micronaut-core/pull/2308

**Comment by graemerocher** [comment]
Documentation for coroutine support https://docs.micronaut.io/snapshot/guide/index.html#coroutines

Will be included in 1.3 M2 to be released soon

**Comment by damianw** [comment]
I am wondering if there is interest in an API for instrumenting the `CoroutineContext` that suspending functions are invoked with by default (since right now it appears they are just given an `EmptyCoroutineContext`). Personally I would like to add an equivalent to `ServerRequestContext` into the `CoroutineContext`, among other things.

Should an issue like that be filed in `micronaut-core` at this point or still in `micronaut-kotlin`?

**Comment by graemerocher** [comment]
I am sure it would be useful. I am not sure where it would belong. Certainly `kotlin-runtime` of this subproject makes sense to me

**Comment by morki** [comment]
For me, suspend functions work, but I need to explicitly name parameters in annotations, autobinding is not working. 

This is working:
```kotlin
// without suspend and without explicit name
@Post("/multipart", consumes = [MediaType.MULTIPART_FORM_DATA])
fun multipart(files: Publisher<CompletedFileUpload>) = "test"

// with suspend and with explicit name 
@Post("/multipart", consumes = [MediaType.MULTIPART_FORM_DATA])
suspend fun multipart(@Part("files") files: Publisher<CompletedFileUpload>) = "test"
```

And this is not:
```kotlin
// with suspend and without explicit name 
@Post("/multipart", consumes = [MediaType.MULTIPART_FORM_DATA])
suspend fun multipart(files: Publisher<CompletedFileUpload>) = "test"
```

Am I missing something or is it a known limitation?

**Comment by graemerocher** [comment]
this is a limitation with KAPT

**Comment by morki** [comment]
Here is the issue to track the limitation of KAPT: https://youtrack.jetbrains.com/issue/KT-43804

**Comment by athkalia** [comment]
Are there plans to add coroutine support in the client as well?

**Comment by jameskleeh** [comment]
Closing this as coroutine support exists in both the client and server
