### ISSUE TITLE
Update the major version of Ktor

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-kotlin#413]
### Issue description

Create next mayor branch for Micronaut Kotlin and update to next mayor version of Ktor

**Comment by wetted** [comment]
See https://ktor.io/docs/migrating-2.html#server

**Comment by wetted** [comment]
duplicate of #403

**Comment by wetted** [comment]
Changes in core are also required:

https://github.com/micronaut-projects/micronaut-core/blob/4.0.x/gradle/libs.versions.toml#L62

**Comment by matejdro** [comment]
Is there a snapshot of this available somewhere? Jfrog link from the readme (https://oss.jfrog.org/artifactory/oss-snapshot-local/) does not appear to contain anything micronaut related.

**Comment by wetted** [comment]
@matejdro Instructions for using SNAPSHOT publications for Micronaut Framework projects can be found in the docs at: https://docs.micronaut.io/latest/guide/#usingsnapshots

Please note this particular PR for this change is merged to the branch of `micronaut-kotlin` that requires Micronaut 4, and that is still under development and not quite ready for use.
