### ISSUE TITLE
Config not resolved

### ISSUE THREAD

**Issue by ddierickx** [micronaut-projects/micronaut-kotlin#42]
Maybe this is desired behavior but `HoconPropertySourceLoader` uses Typesafe Config's `parseURL` creator method which does not resolve the underlying configuration values. This means that value substitution does not work at the moment.

To reproduce this, you can create a small configuration (application.conf) containing an environment variable reference:

`stuff=${STUFF}`

Even when providing the environment variable, the error will be:

> 15:08:35.808 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: need to Config#resolve(), see the API docs for Config#resolve(); substitution not resolved: ConfigReference(${STUFF})
com.typesafe.config.ConfigException$NotResolved: need to Config#resolve(), see the API docs for Config#resolve(); substitution not resolved: ConfigReference(${STUFF})

Is there a reason for this behavior? If not I will submit a PR.

Happy holidays and thanks for your work 🎄.

**Comment by graemerocher** [comment]
No particular reason. PRs welcome!

**Comment by ddierickx** [comment]
Please see #43
