### ISSUE TITLE
Idiomatic kotlin bootstrap

### ISSUE THREAD

**Issue by morki** [micronaut-projects/micronaut-kotlin#44]
I just want to ask, if it can be possible to add some kotlin specific top level bootstrap method for micronaut, for example something like this:

```kotlin
inline fun <reified T : Any> startApplication(vararg args: String, initializer: Micronaut.() -> Unit = {}) {
    Micronaut.build(*args)
        .mainClass(T::class.java)
        .apply(initializer)
        .start()
}

inline fun <reified T : Throwable> Micronaut.mapError(noinline mapper: (T) -> Int): Micronaut {
    return this.mapError(T::class.java, mapper)
}
```

It will simplify micronaut usage for kotlin developers and make it feel more like kotlin specific. The usage then can be like this:

```kotlin
object Application {
    fun main(args: Array<String>) {
        startApplication<Application>(*args) {
            packages("org.example.app")
            mapError<RuntimeException> { 500 }
        }
    }
}
```

I would like to create a PR, but i dont know where to start. I you agree with this addition, can you please point me to the right direction? If not, just close it :)

**Comment by graemerocher** [comment]
A PR would be welcome. I think it probably makes sense to place it in the Kotlin runtime subproject https://github.com/micronaut-projects/micronaut-kotlin/tree/master/kotlin-runtime

**Comment by willbuck** [comment]
Will be incorporated as a part of https://github.com/micronaut-projects/micronaut-kotlin/pull/53
