### ISSUE TITLE
Micronaut Kotlin documentation generation fails

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-kotlin#507]
### Issue description

https://github.com/micronaut-projects/micronaut-kotlin/actions/runs/5072503264/jobs/9110292663

**Comment by sdelamo** [comment]
Still fails @timyates https://github.com/micronaut-projects/micronaut-kotlin/actions/runs/5229578220/jobs/9442644552

**Comment by timyates** [comment]
😠 

Investigating
